server:
  port: 8888 #修改端口号 注意冒号后面需要用空格
  servlet:
    context-path: /sell #加一个前缀
spring:
  druid:
   #url: jdbc:mysql://192.168.1.164:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
   url: jdbc:mysql://192.168.1.164:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
   driverClass: com.mysql.jdbc.Driver
   username: root
   password: 123456
   maxActive: 40 #最大连接数
   maxWait: 10000 #获取连接的最大等待时间
  jpa:
    show-sql: true #显示sql语句
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

wechat:
  appid: wxcec0b9e65c084712
  secret: 05a7e861c1985ced86af77fb8f7163bc